{% set name = "coverage-lcov" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca66692a12c686f337582209d338238a1aafa74149f134387555e719eac4e1e8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - coverage-lcov = coverage_lcov.cli:main

requirements:
  host:
    - pip
    - python >=3.6.3
    - poetry-core >=1.0.0
  run:
    - python >=3.6.3
    - click <8.0.0,>=7.1.2
    - coverage <6.0,>=5.5
    # the following toml dependencies should be provided by coverage but aren't
    - toml >=0.5
    - types-toml <0.2.0,>=0.1.5

test:
  imports:
    - coverage_lcov
  commands:
    - pip check
    - coverage-lcov --help
  requires:
    - pip

about:
  home: https://github.com/TheCleric/coverage-lcov
  license: Apache-2.0
  license_file: LICENSE
  summary: A simple .coverage to LCOV converter

extra:
  recipe-maintainers:
    - tdido
